name: Deploy site files

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - uses: actions/checkout@v2 # 第一步，下载代码仓库

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run build

      # - name: Deploy to Server # 第二步，rsync推文件
      #   uses: up9cloud/action-rsync@v1.3

      #   env:
      #     HOST: ${{ secrets.SSH_HOST }}
      #     KEY: ${{secrets.DEPLOY_KEY}}
      #     TARGET: /webserver/ImgManClient/
      #     SOURCE: ./dist/
      #     SERVER_PORT: "22" # SSH端口
      - uses: burnett01/rsync-deployments@5.2
        name: rsync deployments
        with:
          switches: -avzr --delete --exclude="" --include="" --filter=""
          path: ./dist/
          remote_path: /webserver/ImgManClient/
          remote_host: 101.35.54.147
          remote_port: 22
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}
